# https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-material-for-mkdocs
name: Deploy MkDocs to GitHub Pages
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

# this should fix it when it doesn't work so that it now works
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - run: |
          pip install --upgrade pip
          pip install pytest scipy mkdocs mkdocs-material mkdocs-autorefs mkdocs-jupyter mkdocstrings mkdocstrings-python
          python -m pip install scipy
          python -m pip install opt_einsum
          python -m pip install git+https://github.com/inikishev/torchzero.git
          python -m pip install git+https://github.com/my-unlisted-repos/visualbench.git

      - run: mkdocs gh-deploy --force
